### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by evgeniy97** [lolz0r/ganless-hd#1]
Hi!  
I liked your way to solve the resolution problem without guns. But it a little hard to run your code and unclear how to use it on new images. Will you write a tutorial how to run your code and use it on new images?

**Comment by lolz0r** [comment]
Hi,
To run the code you need to setup your own dataset (directory of images)  and place it into something like `./mydataset/`

Once you have it there update train.py and find where the location of the dataset is specfieid (dataroota):

Update it to:
`parser.add_argument('--dataroota', default=[
	'./mydataset/',
	], type=str)
`
Save changes, and then run:
`python train.py`

From there, everything should work. You will need to ensure that pytorch 0.40 is installed, with python3.
